#!/bin/bash

# Check if any arguments (a message) were provided
if [ $# -eq 0 ]; then
  echo "🛑 Error: No commit message provided."
  echo "Usage: ./gpush.sh your commit message here"
  exit 1
fi

npm run build:all
# Check the exit code of the previous command (npm run build:all)
if [ $? -ne 0 ]; then
  echo "❌ npm build failed. Exiting script."
  exit 1
fi

# Git add all files
echo "Staging all changes..."
git add .

# Git commit with all arguments as the message. The quotes around "$@" are important!
echo "📦 Committing with message: '$@'"
git commit -m "$@"



echo "✅ Success! All changes have been pushed to main."

git status

